services:
  classlog-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/default.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
    ports:
      - 8088:80
    depends_on:
      - classlog-web
    restart: unless-stopped

  classlog-web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - classlog-db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - SECRET_KEY
    restart: unless-stopped
    # volumes:
    #   - .:/app


  classlog-db:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    restart: unless-stopped

volumes:
  pg_data:
