# Generated by Django 5.0.6 on 2024-06-20 10:56

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classname",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="班级名称")),
                (
                    "head_teacher",
                    models.CharField(max_length=20, verbose_name="班主任"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ZB", "中本班"),
                            ("SY", "实验班"),
                            ("ZZ", "中职班"),
                            ("PT", "普通班"),
                        ],
                        default="ZZ",
                        max_length=2,
                        verbose_name="班级类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "班级",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Python", max_length=20, verbose_name="课程名称"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        choices=core.models.year_choices,
                        default=core.models.current_year,
                        verbose_name="年份",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("FA", "Fall"), ("SP", "Spring")],
                        default="FA",
                        max_length=2,
                        verbose_name="学期",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "ordering": ["year", "semester"],
            },
        ),
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="加/减分的原因"),
                ),
                (
                    "is_add",
                    models.BooleanField(default=True, verbose_name="是否是加分"),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=1, verbose_name="分值"),
                ),
            ],
            options={
                "verbose_name": "原因",
                "verbose_name_plural": "原因",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=10, verbose_name="姓名"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "classname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.classname",
                        verbose_name="班级",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "ordering": ["classname__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.reason",
                        verbose_name="原因",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "记录",
                "verbose_name_plural": "记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
