# Generated by Django 5.0.6 on 2024-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('FA', '秋季'), ('SP', '春季')], default='FA', max_length=2, verbose_name='学期'),
        ),
    ]
