# Generated by Django 5.0.6 on 2024-06-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="pinyin",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="拼音"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="pinyin_shortcut",
            field=models.CharField(
                blank=True, default="", max_length=5, verbose_name="拼音缩写"
            ),
        ),
    ]
